export enum ApplicationStatus {
  PROCESSED = 'Processed',
  ENDORSED = 'Endorsed',
  HIRED_APPROVED = 'Approved',
  DEPLOYED = 'Deployed',
    PENDING = 'Pending',
    UNDER_REVIEW = 'under_review',
    SHORTLISTED = 'shortlisted',
    INTERVIEW_SCHEDULED = 'interview_scheduled',
    INTERVIEW_COMPLETED = 'interview_completed',
    DOCUMENT_VERIFICATION = 'document_verification',
    MEDICAL_CHECK = 'medical_check',
    CONTRACT_PREPARATION = 'contract_preparation',
    CONTRACT_SENT = 'contract_sent',
    CONTRACT_SIGNED = 'contract_signed',
    ONBOARDING = 'onboarding',
    COMPLETED = 'completed',
    ON_HOLD = 'on_hold',
    REJECTED = 'rejected',
    CANCEL = 'Cancelled',
    WITHDRAWN = 'withdrawn'
  }
